services:
  backend-dev:
    build:
      context: .
      target: development
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    networks:
      - audit-network

  backend-prod:
    build:
      context: .
      target: production
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:ro
    env_file:
      - .env.local
    networks:
      - audit-network

networks:
  audit-network:
    external: true
